In [7]:
import pandas as pd
import numpy as np
import geopandas as gpd

In [8]:
blocks = gpd.read_file(r'D:\CivicDataLab_IDS-DRR\IDS-DRR_Github\flood-data-ecosystem-Odisha\Maps\od_ids-drr_shapefiles\odisha_block_final.geojson')
blocks

,block_lgd,dtname,dtcode11,block_name,object_id,block_area,geometry
0,03276,Anugul,384,ANUGUL,21-384-03276,1116,"MULTIPOLYGON (((84.82174 20.56003, 84.82096 20..."
1,03277,Anugul,384,ATHMALLIK,21-384-03277,1027,"POLYGON ((84.35602 20.77060, 84.35411 20.77334..."
2,03278,Anugul,384,BANARPAL,21-384-03278,257,"MULTIPOLYGON (((85.08249 20.83019, 85.08400 20..."
3,03279,Anugul,384,CHHENDIPADA,21-384-03279,954,"MULTIPOLYGON (((84.79222 20.87905, 84.79139 20..."
4,03280,Anugul,384,KANIHA,21-384-03280,713,"POLYGON ((84.98528 21.01269, 84.98529 21.01286..."
...,...,...,...,...,...,...,...
309,03585,Sundargarh,374,NUAGAON,21-374-03585,434,"POLYGON ((84.84922 22.34176, 84.84737 22.34209..."
310,03586,Sundargarh,374,RAJGANGPUR,21-374-03586,583,"POLYGON ((84.51444 22.05402, 84.51130 22.05467..."
311,03587,Sundargarh,374,SUBDEGA,21-374-03587,381,"POLYGON ((84.07057 22.11483, 84.07027 22.11518..."
312,03588,Sundargarh,374,SUNDARGARH,21-374-03588,380,"POLYGON ((84.05317 21.93853, 84.05298 21.93870..."
313,03589,Sundargarh,374,TANGARPALI,21-374-03589,331,"POLYGON ((83.99168 22.05358, 83.99253 22.05196..."

In [9]:
districts_df = blocks[['dtname', 'object_id']].copy().reset_index()
districts_df['object_id'] = districts_df['object_id'].str[:6]

# Drop duplicates to ensure each district is listed only once
districts_df = districts_df.drop_duplicates(subset=['object_id']).reset_index()
districts_df

    level_0  index          dtname object_id
0         0      0          Anugul    21-384
1         8      8        Balangir    21-393
2        22     22       Baleshwar    21-377
3        34     34         Bargarh    21-370
4        46     46         Bhadrak    21-378
5        53     53           Boudh    21-391
6        56     56         Cuttack    21-381
7        70     70         Deogarh    21-373
8        73     73       Dhenkanal    21-383
9        81     81        Gajapati    21-389
10       88     88          Ganjam    21-388
11      110    110  Jagatsinghapur    21-380
12      118    118         Jajapur    21-382
13      128    128      Jharsuguda    21-371
14      133    133       Kalahandi    21-395
15      146    146       Kandhamal    21-390
16      158    158      Kendrapara    21-379
17      167    167       Kendujhar    21-375
18      180    180         Khordha    21-386
19      190    190         Koraput    21-398
20      204    204      Malkangiri    21-399
21      211    211      Mayurbhanj    21-376
22      237    237     Nabarangpur    21-397
23      247    247        Nayagarh    21-385
24      255    255         Nuapada    21-394
25      260    260            Puri    21-387
26      271    271        Rayagada    21-396
27      282    282       Sambalpur    21-372
28      291    291         Sonepur    21-392
29      297    297      Sundargarh    21-374

In [10]:
districts_df.to_csv(r'D:\CivicDataLab_IDS-DRR\IDS-DRR_Github\flood-data-ecosystem-Odisha\RiskScoreModel\assets\district_objectid.csv')